In [123]:
import spotipy
import pandas as pd
import random
from sklearn.neighbors import NearestNeighbors
from spotipy.oauth2 import SpotifyClientCredentials

In [124]:
#Authentication - without user
client_credentials_manager = SpotifyClientCredentials(client_id="f99b4dafd3504ab389e943951d0efa39", client_secret="13b6230cb77e4f46a8d2eabb27292750")
sp = spotipy.Spotify(client_credentials_manager = client_credentials_manager)

In [125]:
playlist_link = "https://open.spotify.com/playlist/78Sdax2ygDKQiVtbUtzjWQ"
playlist_URI = playlist_link.split("/")[-1].split("?")[0]
track_uris = [x["track"]["uri"] for x in sp.playlist_tracks(playlist_URI)["items"]]

In [126]:
# Retrieve the list of tracks in the playlist
results = sp.playlist_tracks(playlist_URI)
tracks = results['items']
while results['next']:
    results = sp.next(results)
    tracks.extend(results['items'])

In [127]:
track_artist = track_uris[99]
track_artist

'spotify:track:2dRj9RAkUWmsWeYnKR1ohe'

In [128]:
features  = []
for i in range(100):
    features.append(sp.audio_features(track_uris)[i])

In [129]:
features[99]

{'danceability': 0.782,
 'energy': 0.446,
 'key': 6,
 'loudness': -7.066,
 'mode': 0,
 'speechiness': 0.058,
 'acousticness': 0.325,
 'instrumentalness': 0,
 'liveness': 0.209,
 'valence': 0.704,
 'tempo': 139.914,
 'type': 'audio_features',
 'id': '2dRj9RAkUWmsWeYnKR1ohe',
 'uri': 'spotify:track:2dRj9RAkUWmsWeYnKR1ohe',
 'track_href': 'https://api.spotify.com/v1/tracks/2dRj9RAkUWmsWeYnKR1ohe',
 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/2dRj9RAkUWmsWeYnKR1ohe',
 'duration_ms': 225835,
 'time_signature': 4}

In [130]:
details = []
emotions = ["happy","sad","fear","normal","angry"]
for i,track in enumerate(tracks):
  track_name = track['track']['name']
  track_artist = track['track']['artists'][0]['name']
  track_album = track['track']['album']['name']
  track_popularity = track['track']['popularity']
  track_emotion = random.choice(emotions)
  track_acousticness = features[i]['acousticness']
  track_id = features[i]['id']
  track_energy = features[i]['energy']
  track_loudness = features[i]['loudness']
  track_liveness = features[i]['liveness']
  track_danceability = features[i]['danceability']
  track_speechiness = features[i]['speechiness']
  track_instrumentalness = features[i]['instrumentalness']
  track_tempo = features[i]['tempo']


  details.append({
    'name': track_name,
    'artist': track_artist,
    'album': track_album,
    'popularity': track_popularity,
    'emotion': track_emotion,
    'acousticness': track_acousticness,
    'id': track_id,
    'energy': track_energy,
    'loudness': track_loudness,
    'liveness': track_liveness,
    'danceability': track_danceability,
    'speechiness': track_speechiness,
    'instrumentalness': track_instrumentalness,
    'tempo': track_tempo

  })

In [131]:
df1 = pd.DataFrame(details)
print(df1)

                                                 name               artist  \
0                              Mannarkudi Kalakalakka    Manikka Vinayagam
1                             Ada All Thotta Boopathi          Mani Sharma
2                       Jalsa (From "Chennai-600028")       Ranjith Govind
3                               Madura Palapalakkuthu     Nivas K Prasanna
4                                Kanadhasan Karaikudi              Myskkin
..                                                ...                  ...
95               Ra Ra Rakkamma (From "Vikrant Rona")          Nakash Aziz
96                   Aathangara Orathil (From "Yaan")       Harris Jayaraj
97                                 Dosti (From "RRR")   Hemachandra Vedala
98  Dippam Dappam (From "Kaathuvaakula Rendu Kaadh...  Anirudh Ravichander
99                                     En Kannu Kulla             Vishal C

                                                album  popularity emotion  \
0                                     Sivappathigaram          56     sad
1          Youth (Original Motion Picture Soundtrack)          53   happy
2                         Ranjith Hits at Yuvan Music          54   angry
3     Devarattam (Original Motion Picture Soundtrack)          51   happy
4        Anjathe (Original Motion Picture Soundtrack)          54     sad
..                                                ...         ...     ...
95               Ra Ra Rakkamma (From "Vikrant Rona")          62     sad
96           20 Biggest Hits : Harris Jayaraj, Vol. 2          48   happy
97                                 Dosti (From "RRR")          56   happy
98  Dippam Dappam (From "Kaathuvaakula Rendu Kaadh...          70    fear
99  Appuchi Graamam (Original Motion Picture Sound...          50  normal

    acousticness                      id  energy  loudness  liveness  \
0        0.24500  2tUChcOi3ktjFzMYu2w5QL   0.906    -6.251    0.0299
1        0.21600  2ROdfODv25pRFi0UmK2CcM   0.894    -8.421    0.0620
2        0.01090  0n84wNo6l1WDuAPDy5uM7Z   0.593    -7.717    0.8130
3        0.28000  2gfcDc4XwShheQU9QrR4ao   0.907    -6.406    0.0425
4        0.08120  4pAwoYbUmrAw41LlFZc8Hz   0.635    -5.676    0.0806
..           ...                     ...     ...       ...       ...
95       0.43100  0stbF4C1ACmIvx0aW81ZXa   0.972    -5.720    0.0907
96       0.00912  6SkMXIqCaFtWwtwXLHVpmz   0.643    -7.015    0.0997
97       0.50700  6h5vL07MyGY6WdWPYK4IMG   0.690    -8.609    0.1080
98       0.09080  2vkNA9I029dTwX0y6d59Sc   0.717    -7.755    0.0511
99       0.32500  2dRj9RAkUWmsWeYnKR1ohe   0.446    -7.066    0.2090

    danceability  speechiness  instrumentalness    tempo
0          0.701       0.1520          0.000056  157.841
1          0.771       0.2410          0.000001   77.005
2          0.902       0.1290          0.003470   99.999
3          0.483       0.3370          0.000000   89.084
4          0.698       0.0601          0.000000  172.415
..           ...          ...               ...      ...
95         0.839       0.1020          0.000200  130.012
96         0.935       0.2360          0.000000   98.984
97         0.681       0.0449          0.000090   75.002
98         0.827       0.1110          0.000523  123.987
99         0.782       0.0580          0.000000  139.914

[100 rows x 14 columns]

In [132]:
df1['album'] = df['album'].str.split('(').str[0]
c = df1
df1.head()

,name,artist,album,popularity,emotion,acousticness,id,energy,loudness,liveness,danceability,speechiness,instrumentalness,tempo
0,Mannarkudi Kalakalakka,Manikka Vinayagam,I,56,sad,0.2450,2tUChcOi3ktjFzMYu2w5QL,0.906,-6.251,0.0299,0.701,0.1520,0.000056,157.841
1,Ada All Thotta Boopathi,Mani Sharma,Maryan,53,happy,0.2160,2ROdfODv25pRFi0UmK2CcM,0.894,-8.421,0.0620,0.771,0.2410,0.000001,77.005
2,"Jalsa (From ""Chennai-600028"")",Ranjith Govind,Vinnathaandi Varuvaayaa,54,angry,0.0109,0n84wNo6l1WDuAPDy5uM7Z,0.593,-7.717,0.8130,0.902,0.1290,0.003470,99.999
3,Madura Palapalakkuthu,Nivas K Prasanna,Roja,51,happy,0.2800,2gfcDc4XwShheQU9QrR4ao,0.907,-6.406,0.0425,0.483,0.3370,0.000000,89.084
4,Kanadhasan Karaikudi,Myskkin,Achcham Yenbadhu Madamaiyada,54,sad,0.0812,4pAwoYbUmrAw41LlFZc8Hz,0.635,-5.676,0.0806,0.698,0.0601,0.000000,172.415

In [133]:
df1['popularity'].describe()

count    100.000000
mean      56.520000
std       13.307156
min        0.000000
25%       51.750000
50%       57.000000
75%       64.000000
max       83.000000
Name: popularity, dtype: float64

In [134]:
df1['popularity'] = df1['popularity'].apply(lambda x: int(x/5))
df1.head()

,name,artist,album,popularity,emotion,acousticness,id,energy,loudness,liveness,danceability,speechiness,instrumentalness,tempo
0,Mannarkudi Kalakalakka,Manikka Vinayagam,I,11,sad,0.2450,2tUChcOi3ktjFzMYu2w5QL,0.906,-6.251,0.0299,0.701,0.1520,0.000056,157.841
1,Ada All Thotta Boopathi,Mani Sharma,Maryan,10,happy,0.2160,2ROdfODv25pRFi0UmK2CcM,0.894,-8.421,0.0620,0.771,0.2410,0.000001,77.005
2,"Jalsa (From ""Chennai-600028"")",Ranjith Govind,Vinnathaandi Varuvaayaa,10,angry,0.0109,0n84wNo6l1WDuAPDy5uM7Z,0.593,-7.717,0.8130,0.902,0.1290,0.003470,99.999
3,Madura Palapalakkuthu,Nivas K Prasanna,Roja,10,happy,0.2800,2gfcDc4XwShheQU9QrR4ao,0.907,-6.406,0.0425,0.483,0.3370,0.000000,89.084
4,Kanadhasan Karaikudi,Myskkin,Achcham Yenbadhu Madamaiyada,10,sad,0.0812,4pAwoYbUmrAw41LlFZc8Hz,0.635,-5.676,0.0806,0.698,0.0601,0.000000,172.415

In [135]:
emotions_encoded = pd.get_dummies(df['emotion'], prefix='emotion')
emotions_encoded

    emotion_angry  emotion_fear  emotion_happy  emotion_normal  emotion_sad
0               0             1              0               0            0
1               0             0              1               0            0
2               0             0              0               0            1
3               0             0              0               1            0
4               0             0              0               0            1
..            ...           ...            ...             ...          ...
95              0             0              0               1            0
96              0             0              0               0            1
97              1             0              0               0            0
98              0             0              0               1            0
99              0             0              1               0            0

[100 rows x 5 columns]

In [136]:
emotions_df = df1
emotions_df

,name,artist,album,popularity,emotion,acousticness,id,energy,loudness,liveness,danceability,speechiness,instrumentalness,tempo
0,Mannarkudi Kalakalakka,Manikka Vinayagam,I,11,sad,0.24500,2tUChcOi3ktjFzMYu2w5QL,0.906,-6.251,0.0299,0.701,0.1520,0.000056,157.841
1,Ada All Thotta Boopathi,Mani Sharma,Maryan,10,happy,0.21600,2ROdfODv25pRFi0UmK2CcM,0.894,-8.421,0.0620,0.771,0.2410,0.000001,77.005
2,"Jalsa (From ""Chennai-600028"")",Ranjith Govind,Vinnathaandi Varuvaayaa,10,angry,0.01090,0n84wNo6l1WDuAPDy5uM7Z,0.593,-7.717,0.8130,0.902,0.1290,0.003470,99.999
3,Madura Palapalakkuthu,Nivas K Prasanna,Roja,10,happy,0.28000,2gfcDc4XwShheQU9QrR4ao,0.907,-6.406,0.0425,0.483,0.3370,0.000000,89.084
4,Kanadhasan Karaikudi,Myskkin,Achcham Yenbadhu Madamaiyada,10,sad,0.08120,4pAwoYbUmrAw41LlFZc8Hz,0.635,-5.676,0.0806,0.698,0.0601,0.000000,172.415
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,"Ra Ra Rakkamma (From ""Vikrant Rona"")",Nakash Aziz,Minsara Kanavu,12,sad,0.43100,0stbF4C1ACmIvx0aW81ZXa,0.972,-5.720,0.0907,0.839,0.1020,0.000200,130.012
96,"Aathangara Orathil (From ""Yaan"")",Harris Jayaraj,Minsara Kanavu,9,happy,0.00912,6SkMXIqCaFtWwtwXLHVpmz,0.643,-7.015,0.0997,0.935,0.2360,0.000000,98.984
97,"Dosti (From ""RRR"")",Hemachandra Vedala,SPB - The Voice For A Millennium,11,happy,0.50700,6h5vL07MyGY6WdWPYK4IMG,0.690,-8.609,0.1080,0.681,0.0449,0.000090,75.002
98,"Dippam Dappam (From ""Kaathuvaakula Rendu Kaadh...",Anirudh Ravichander,Dil Hi Dil Mein,14,fear,0.09080,2vkNA9I029dTwX0y6d59Sc,0.717,-7.755,0.0511,0.827,0.1110,0.000523,123.987
99,En Kannu Kulla,Vishal C,Hits of A.R.Rahman Nenjame,10,normal,0.32500,2dRj9RAkUWmsWeYnKR1ohe,0.446,-7.066,0.2090,0.782,0.0580,0.000000,139.914

In [137]:
d = ['name','artist','album','id']
df1 = df1[d]
df1

,name,artist,album,id
0,Mannarkudi Kalakalakka,Manikka Vinayagam,I,2tUChcOi3ktjFzMYu2w5QL
1,Ada All Thotta Boopathi,Mani Sharma,Maryan,2ROdfODv25pRFi0UmK2CcM
2,"Jalsa (From ""Chennai-600028"")",Ranjith Govind,Vinnathaandi Varuvaayaa,0n84wNo6l1WDuAPDy5uM7Z
3,Madura Palapalakkuthu,Nivas K Prasanna,Roja,2gfcDc4XwShheQU9QrR4ao
4,Kanadhasan Karaikudi,Myskkin,Achcham Yenbadhu Madamaiyada,4pAwoYbUmrAw41LlFZc8Hz
...,...,...,...,...
95,"Ra Ra Rakkamma (From ""Vikrant Rona"")",Nakash Aziz,Minsara Kanavu,0stbF4C1ACmIvx0aW81ZXa
96,"Aathangara Orathil (From ""Yaan"")",Harris Jayaraj,Minsara Kanavu,6SkMXIqCaFtWwtwXLHVpmz
97,"Dosti (From ""RRR"")",Hemachandra Vedala,SPB - The Voice For A Millennium,6h5vL07MyGY6WdWPYK4IMG
98,"Dippam Dappam (From ""Kaathuvaakula Rendu Kaadh...",Anirudh Ravichander,Dil Hi Dil Mein,2vkNA9I029dTwX0y6d59Sc
99,En Kannu Kulla,Vishal C,Hits of A.R.Rahman Nenjame,2dRj9RAkUWmsWeYnKR1ohe

In [138]:
emotions_df = emotions_df.drop(['name','artist','album','id','popularity','emotion'], axis=1)
emotions_normalized = (emotions_df - emotions_df.mean()) / emotions_df.std()
emotions_normalized

,acousticness,energy,loudness,liveness,danceability,speechiness,instrumentalness,tempo
0,-0.414713,1.285295,0.408617,-0.846217,0.150403,0.344557,-0.205856,1.389490
1,-0.539803,1.215698,-0.454493,-0.664861,0.652224,1.146964,-0.207628,-1.288932
2,-1.424490,-0.530044,-0.174480,3.578089,1.591346,0.137193,-0.096117,-0.527048
3,-0.263742,1.291095,0.346967,-0.775030,-1.412411,2.012481,-0.207663,-0.888706
4,-1.121255,-0.286453,0.637322,-0.559776,0.128896,-0.483995,-0.207663,1.872386
...,...,...,...,...,...,...,...,...
95,0.387588,1.668083,0.619821,-0.502713,1.139707,-0.106233,-0.201234,0.467404
96,-1.432168,-0.240054,0.104739,-0.451866,1.827919,1.101885,-0.207663,-0.560679
97,0.715410,0.032537,-0.529270,-0.404973,0.007025,-0.621036,-0.204757,-1.355299
98,-1.079846,0.189132,-0.189594,-0.726443,1.053681,-0.025091,-0.190850,0.267771
99,-0.069637,-1.382616,0.084454,0.165650,0.731082,-0.502929,-0.207663,0.795497

In [139]:
emotions_df

,acousticness,energy,loudness,liveness,danceability,speechiness,instrumentalness,tempo
0,0.24500,0.906,-6.251,0.0299,0.701,0.1520,0.000056,157.841
1,0.21600,0.894,-8.421,0.0620,0.771,0.2410,0.000001,77.005
2,0.01090,0.593,-7.717,0.8130,0.902,0.1290,0.003470,99.999
3,0.28000,0.907,-6.406,0.0425,0.483,0.3370,0.000000,89.084
4,0.08120,0.635,-5.676,0.0806,0.698,0.0601,0.000000,172.415
...,...,...,...,...,...,...,...,...
95,0.43100,0.972,-5.720,0.0907,0.839,0.1020,0.000200,130.012
96,0.00912,0.643,-7.015,0.0997,0.935,0.2360,0.000000,98.984
97,0.50700,0.690,-8.609,0.1080,0.681,0.0449,0.000090,75.002
98,0.09080,0.717,-7.755,0.0511,0.827,0.1110,0.000523,123.987
99,0.32500,0.446,-7.066,0.2090,0.782,0.0580,0.000000,139.914

In [140]:
emotions_df.mean()

acousticness          0.341144
energy                0.684390
loudness             -7.278330
liveness              0.179680
danceability          0.680020
speechiness           0.113783
instrumentalness      0.006460
tempo               115.905550
dtype: float64

In [141]:
emotions_df.std()

acousticness         0.231833
energy               0.172419
loudness             2.514161
liveness             0.177000
danceability         0.139492
speechiness          0.110916
instrumentalness     0.031108
tempo               30.180452
dtype: float64

In [142]:
emotions_normalized = emotions_df - emotions_df.mean()
emotions_normalized

,acousticness,energy,loudness,liveness,danceability,speechiness,instrumentalness,tempo
0,-0.096144,0.22161,1.02733,-0.14978,0.02098,0.038217,-0.006404,41.93545
1,-0.125144,0.20961,-1.14267,-0.11768,0.09098,0.127217,-0.006459,-38.90055
2,-0.330244,-0.09139,-0.43867,0.63332,0.22198,0.015217,-0.002990,-15.90655
3,-0.061144,0.22261,0.87233,-0.13718,-0.19702,0.223217,-0.006460,-26.82155
4,-0.259944,-0.04939,1.60233,-0.09908,0.01798,-0.053683,-0.006460,56.50945
...,...,...,...,...,...,...,...,...
95,0.089856,0.28761,1.55833,-0.08898,0.15898,-0.011783,-0.006260,14.10645
96,-0.332024,-0.04139,0.26333,-0.07998,0.25498,0.122217,-0.006460,-16.92155
97,0.165856,0.00561,-1.33067,-0.07168,0.00098,-0.068883,-0.006370,-40.90355
98,-0.250344,0.03261,-0.47667,-0.12858,0.14698,-0.002783,-0.005937,8.08145
99,-0.016144,-0.23839,0.21233,0.02932,0.10198,-0.055783,-0.006460,24.00845

In [143]:
train = pd.concat([emotions_encoded, emotions_normalized], axis=1)
normalized = pd.concat([df1, emotions_encoded, emotions_normalized], axis=1)
normalized

,name,artist,album,id,emotion_angry,emotion_fear,emotion_happy,emotion_normal,emotion_sad,acousticness,energy,loudness,liveness,danceability,speechiness,instrumentalness,tempo
0,Mannarkudi Kalakalakka,Manikka Vinayagam,I,2tUChcOi3ktjFzMYu2w5QL,0,1,0,0,0,-0.096144,0.22161,1.02733,-0.14978,0.02098,0.038217,-0.006404,41.93545
1,Ada All Thotta Boopathi,Mani Sharma,Maryan,2ROdfODv25pRFi0UmK2CcM,0,0,1,0,0,-0.125144,0.20961,-1.14267,-0.11768,0.09098,0.127217,-0.006459,-38.90055
2,"Jalsa (From ""Chennai-600028"")",Ranjith Govind,Vinnathaandi Varuvaayaa,0n84wNo6l1WDuAPDy5uM7Z,0,0,0,0,1,-0.330244,-0.09139,-0.43867,0.63332,0.22198,0.015217,-0.002990,-15.90655
3,Madura Palapalakkuthu,Nivas K Prasanna,Roja,2gfcDc4XwShheQU9QrR4ao,0,0,0,1,0,-0.061144,0.22261,0.87233,-0.13718,-0.19702,0.223217,-0.006460,-26.82155
4,Kanadhasan Karaikudi,Myskkin,Achcham Yenbadhu Madamaiyada,4pAwoYbUmrAw41LlFZc8Hz,0,0,0,0,1,-0.259944,-0.04939,1.60233,-0.09908,0.01798,-0.053683,-0.006460,56.50945
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,"Ra Ra Rakkamma (From ""Vikrant Rona"")",Nakash Aziz,Minsara Kanavu,0stbF4C1ACmIvx0aW81ZXa,0,0,0,1,0,0.089856,0.28761,1.55833,-0.08898,0.15898,-0.011783,-0.006260,14.10645
96,"Aathangara Orathil (From ""Yaan"")",Harris Jayaraj,Minsara Kanavu,6SkMXIqCaFtWwtwXLHVpmz,0,0,0,0,1,-0.332024,-0.04139,0.26333,-0.07998,0.25498,0.122217,-0.006460,-16.92155
97,"Dosti (From ""RRR"")",Hemachandra Vedala,SPB - The Voice For A Millennium,6h5vL07MyGY6WdWPYK4IMG,1,0,0,0,0,0.165856,0.00561,-1.33067,-0.07168,0.00098,-0.068883,-0.006370,-40.90355
98,"Dippam Dappam (From ""Kaathuvaakula Rendu Kaadh...",Anirudh Ravichander,Dil Hi Dil Mein,2vkNA9I029dTwX0y6d59Sc,0,0,0,1,0,-0.250344,0.03261,-0.47667,-0.12858,0.14698,-0.002783,-0.005937,8.08145
99,En Kannu Kulla,Vishal C,Hits of A.R.Rahman Nenjame,2dRj9RAkUWmsWeYnKR1ohe,0,0,1,0,0,-0.016144,-0.23839,0.21233,0.02932,0.10198,-0.055783,-0.006460,24.00845

In [144]:
nn = NearestNeighbors(n_neighbors=20, algorithm='ball_tree')
nn.fit(train)

NearestNeighbors(algorithm='ball_tree', n_neighbors=20)

In [149]:
def recommend_songs(emotion, num_to_select):
    num_songs=20
    # create a new array with the normalized features for the input emotion
    input_emotion = train.loc[train[f"emotion_{emotion}"] == 1].values[:, 0:]
    # find the nearest neighbors for the input emotion
    distances, indices = nn.kneighbors(input_emotion)
    # randomly select a subset of the top recommended songs
    top_songs = df1.iloc[indices[0]][['name', 'artist']].head(num_songs)
    selected_songs = top_songs.sample(n=num_to_select, replace=False)
    return selected_songs

In [150]:
recommend_songs('happy', 10)

C:\Users\arohi\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(

                                            name              artist
75                                    Kalaavathi            Thaman S
66  Theemai Dhaan Vellum - Awakening the Monster      Hiphop Tamizha
22                                  Pottu Thakku       Srikanth Deva
38                          Kan Pesum Varthaigal             Karthik
97                            Dosti (From "RRR")  Hemachandra Vedala
40                               The Life of Ram     Govind Vasantha
1                        Ada All Thotta Boopathi         Mani Sharma
61                                     Mehabooba         Ananya Bhat
44                                    Oru Naalil  Yuvan Shankar Raja
53                              Althota Boopathy   Shankar Mahadevan